<?php 

return [

    'compound_id_type' => [
        #: Original Deposited Compound
        'DEPOSITED' => 0,
        #: Standardized Form of the Deposited Compound
        'STANDARDIZED' => 1,
        #: Component of the Standardized Form
        'COMPONENT' => 2,
        #: Neutralized Form of the Standardized Form
        'NEUTRALIZED' => 3,
        #: Deposited Mixture Component
        'MIXTURE' => 4,
        #: Alternate Tautomer Form of the Standardized Form
        'TAUTOMER' => 5,
        #: Ionized pKa Form of the Standardized Form
        'IONIZED' => 6,
        #: Unspecified or Unknown Compound Type
        'UNKNOWN' => 255,
    ],

    'bond_type' => [
        'SINGLE' => 1,
        'DOUBLE' => 2,
        'TRIPLE' => 3,
        'QUADRUPLE' => 4,
        'DATIVE' => 5,
        'COMPLEX' => 6,
        'IONIC' => 7,
        'UNKNOWN' => 255,
    ],

    'coordinate_type' => [
        'TWO_D' => 1,
        'THREE_D' => 2,
        'SUBMITTED' => 3,
        'EXPERIMENTAL' => 4,
        'COMPUTED' => 5,
        'STANDARDIZED' => 6,
        'AUGMENTED' => 7,
        'ALIGNED' => 8,
        'COMPACT' => 9,
        'UNITS_ANGSTROMS' => 10,
        'UNITS_NANOMETERS' => 11,
        'UNITS_PIXEL' => 12,
        'UNITS_POINTS' => 13,
        'UNITS_STDBONDS' => 14,
        'UNITS_UNKNOWN' => 255,
    ],

    'project_category' => [
        'MLSCN' => 1,
        'MPLCN' => 2,
        'MLSCN_AP' => 3,
        'MPLCN_AP' => 4,
        'JOURNAL_ARTICLE' => 5,
        'ASSAY_VENDOR' => 6,
        'LITERATURE_EXTRACTED' => 7,
        'LITERATURE_AUTHOR' => 8,
        'LITERATURE_PUBLISHER' => 9,
        'RNAIGI' => 10,
        'OTHER' => 255,
    ],

    'elements' => [
        1 => 'H',
        2 => 'He',
        3 => 'Li',
        4 => 'Be',
        5 => 'B',
        6 => 'C',
        7 => 'N',
        8 => 'O',
        9 => 'F',
        10 => 'Ne',
        11 => 'Na',
        12 => 'Mg',
        13 => 'Al',
        14 => 'Si',
        15 => 'P',
        16 => 'S',
        17 => 'Cl',
        18 => 'Ar',
        19 => 'K',
        20 => 'Ca',
        21 => 'Sc',
        22 => 'Ti',
        23 => 'V',
        24 => 'Cr',
        25 => 'Mn',
        26 => 'Fe',
        27 => 'Co',
        28 => 'Ni',
        29 => 'Cu',
        30 => 'Zn',
        31 => 'Ga',
        32 => 'Ge',
        33 => 'As',
        34 => 'Se',
        35 => 'Br',
        36 => 'Kr',
        37 => 'Rb',
        38 => 'Sr',
        39 => 'Y',
        40 => 'Zr',
        41 => 'Nb',
        42 => 'Mo',
        43 => 'Tc',
        44 => 'Ru',
        45 => 'Rh',
        46 => 'Pd',
        47 => 'Ag',
        48 => 'Cd',
        49 => 'In',
        50 => 'Sn',
        51 => 'Sb',
        52 => 'Te',
        53 => 'I',
        54 => 'Xe',
        55 => 'Cs',
        56 => 'Ba',
        57 => 'La',
        58 => 'Ce',
        59 => 'Pr',
        60 => 'Nd',
        61 => 'Pm',
        62 => 'Sm',
        63 => 'Eu',
        64 => 'Gd',
        65 => 'Tb',
        66 => 'Dy',
        67 => 'Ho',
        68 => 'Er',
        69 => 'Tm',
        70 => 'Yb',
        71 => 'Lu',
        72 => 'Hf',
        73 => 'Ta',
        74 => 'W',
        75 => 'Re',
        76 => 'Os',
        77 => 'Ir',
        78 => 'Pt',
        79 => 'Au',
        80 => 'Hg',
        81 => 'Tl',
        82 => 'Pb',
        83 => 'Bi',
        84 => 'Po',
        85 => 'At',
        86 => 'Rn',
        87 => 'Fr',
        88 => 'Ra',
        89 => 'Ac',
        90 => 'Th',
        91 => 'Pa',
        92 => 'U',
        93 => 'Np',
        94 => 'Pu',
        95 => 'Am',
        96 => 'Cm',
        97 => 'Bk',
        98 => 'Cf',
        99 => 'Es',
        100 => 'Fm',
        101 => 'Md',
        102 => 'No',
        103 => 'Lr',
        104 => 'Rf',
        105 => 'Db',
        106 => 'Sg',
        107 => 'Bh',
        108 => 'Hs',
        109 => 'Mt',
        110 => 'Ds',
        111 => 'Rg',
        112 => 'Cp',
        113 => 'ut',
        114 => 'uq',
        115 => 'up',
        116 => 'uh',
        117 => 'us',
        118 => 'uo',
    ],
];
